name: Format and test

on:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, closed ]

jobs:
  format-and-test:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install rust.
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --all-features

